debug: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:38080/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
server:
  port: 48080
spring:
  application:
    name: routerZuul-0
zuul:
  routes:
    # 这里可以自定义
    main:
      # 匹配的路由规则
      path: /main/**
      service-id: consumer-0 # 路由的目标服务名